### ISSUE TITLE
Incompatibility with pyproj version 1.9.6 used by pypsa-eur

### ISSUE THREAD

**Issue by Svosw** [PyPSA/atlite#53]
I have already [filed the issue with pyproj-eur](https://github.com/PyPSA/pypsa-eur/issues/119) and was asked to file it here as well.

The error happens when importing atlite with pyproj version 1.9.6 installed.

Steps to reproduce the error:
1. Create an environment with pyproj=1.9.6 and atlite
2. Open a python console
3. `import atlite`.

## Possible solution
Add `ellps=XXX` (e.g. `ellps='WGS84'`, if WGS84 is correct) to the call `projection = RotProj(dict(proj='ob_tran', o_proj='latlong', lon_0=180, o_lon_p=-162, o_lat_p=39.25))` on line 41/42 in `cordex.py`.

## Error Message for atlite
```python
>>> import atlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Svosw\miniconda3\envs\pyproj_test\lib\site-packages\atlite\__init__.py", line 26, in <module>
    from .cutout import Cutout
  File "C:\Users\Svosw\miniconda3\envs\pyproj_test\lib\site-packages\atlite\cutout.py", line 33, in <module>
    from . import config, datasets
  File "C:\Users\Svosw\miniconda3\envs\pyproj_test\lib\site-packages\atlite\datasets\__init__.py", line 3, in <module>
    from . import cordex, ncep, era5, sarah
  File "C:\Users\Svosw\miniconda3\envs\pyproj_test\lib\site-packages\atlite\datasets\cordex.py", line 42, in <module>
    o_lon_p=-162, o_lat_p=39.25))
  File "C:\Users\Svosw\miniconda3\envs\pyproj_test\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'major axis or radius = 0 or not given'
```

**Comment by coroa** [comment]
I think the underlying latlong projection is related to WGS84 as in mentioned something about it, yes. But to be honest I don't know what the ellipsis is for.

Can you explain in any more detail of what is happening and why choosing an ellipsis is necessary here? (or link to some documentation).

Thanks

**Comment by Svosw** [comment]
Unfortunately I don't have any more information, I just found the suggestion for including `ellps='WGS84` [here](https://github.com/OSGeo/PROJ/issues/398).

**Comment by coroa** [comment]
Problem is solved by using up-to-date pyproj. See https://github.com/PyPSA/pypsa-eur/pull/120.
