### ISSUE TITLE
Problem locally installing `v0.2` using `pip`

### ISSUE THREAD

**Issue by euronion** [PyPSA/atlite#96]
I am unable to locally install the current version with `pip` (`pip install .`).
I am using the `environment.yaml` file provided.

The following error message pops up when trying install it:
```
(atlite) pypsa@vm-pypsa:~/share/GitHub/atlite$ git remote -v
origin  https://github.com/PyPSA/atlite.git (fetch)
origin  https://github.com/PyPSA/atlite.git (push)
(atlite) pypsa@vm-pypsa:~/share/GitHub/atlite$ git status
On branch v0.2
Your branch is up-to-date with 'origin/v0.2'.

nothing to commit, working tree clean
(atlite) pypsa@vm-pypsa:~/share/GitHub/atlite$ pip install .
Processing /home/pypsa/share/GitHub/atlite
    ERROR: Command errored out with exit status 1:
     command: /home/pypsa/miniconda3/envs/atlite/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-egexmm80/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-egexmm80/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-egexmm80/pip-egg-info
         cwd: /tmp/pip-req-build-egexmm80/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-egexmm80/setup.py", line 52, in <module>
        'Operating System :: OS Independent',
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/__init__.py", line 160, in setup
        _install_setup_requires(attrs)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/wheel.py", line 99, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/wheel.py", line 107, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages/setuptools/wheel.py", line 128, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [Errno 17] File exists: '/tmp/pip-req-build-egexmm80/.eggs/setuptools_scm-4.1.2-py3.7.egg'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Installing it directly from GitHub works fine, i.e. this works w/o problems:

```
(atlite) pypsa@vm-pypsa:~/share/GitHub/atlite$ pip install git+https://github.com/pypsa/atlite.git@v0.2
Collecting git+https://github.com/pypsa/atlite.git@v0.2
  Cloning https://github.com/pypsa/atlite.git (to revision v0.2) to /tmp/pip-req-build-v4bvq5v1
  Running command git clone -q https://github.com/pypsa/atlite.git /tmp/pip-req-build-v4bvq5v1
  Running command git checkout -b v0.2 --track origin/v0.2
  Switched to a new branch 'v0.2'
  Branch 'v0.2' set up to track remote branch 'v0.2' from 'origin'.
Requirement already satisfied: numpy in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.18.1)
Requirement already satisfied: scipy in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.4.1)
Requirement already satisfied: pandas>=0.22 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.0.3)
Requirement already satisfied: bottleneck in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.3.2)
Requirement already satisfied: numexpr in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (2.7.1)
Requirement already satisfied: xarray>=0.11.2 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (0.15.1)
Requirement already satisfied: netcdf4 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.4.2)
Requirement already satisfied: dask>=0.18.0 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (2.17.2)
Requirement already satisfied: requests in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (2.23.0)
Requirement already satisfied: rtree in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (0.9.4)
Requirement already satisfied: pyyaml in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (5.3.1)
Requirement already satisfied: rasterio>=1.0 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.1.0)
Requirement already satisfied: shapely in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (1.7.0)
Requirement already satisfied: progressbar2 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (3.37.1)
Requirement already satisfied: geopandas in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (0.6.1)
Requirement already satisfied: cdsapi in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from atlite==0.0.4.dev330+g2fbdd9f) (0.2.7)
Requirement already satisfied: pytz>=2017.2 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from pandas>=0.22->atlite==0.0.4.dev330+g2fbdd9f) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from pandas>=0.22->atlite==0.0.4.dev330+g2fbdd9f) (2.8.1)
Requirement already satisfied: setuptools>=41.2 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from xarray>=0.11.2->atlite==0.0.4.dev330+g2fbdd9f) (47.1.1.post20200604)
Requirement already satisfied: cftime in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from netcdf4->atlite==0.0.4.dev330+g2fbdd9f) (1.1.2)
Requirement already satisfied: idna<3,>=2.5 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from requests->atlite==0.0.4.dev330+g2fbdd9f) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from requests->atlite==0.0.4.dev330+g2fbdd9f) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from requests->atlite==0.0.4.dev330+g2fbdd9f) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from requests->atlite==0.0.4.dev330+g2fbdd9f) (2020.4.5.1)
Requirement already satisfied: attrs in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (19.3.0)
Requirement already satisfied: snuggs>=1.4.1 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (1.4.7)
Requirement already satisfied: cligj>=0.5 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (0.5.0)
Requirement already satisfied: affine in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (2.3.0)
Requirement already satisfied: click<8,>=4.0 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (7.1.2)
Requirement already satisfied: click-plugins in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (1.1.1)
Requirement already satisfied: python-utils>=2.3.0 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from progressbar2->atlite==0.0.4.dev330+g2fbdd9f) (2.3.0)
Requirement already satisfied: six in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from progressbar2->atlite==0.0.4.dev330+g2fbdd9f) (1.15.0)
Requirement already satisfied: fiona in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from geopandas->atlite==0.0.4.dev330+g2fbdd9f) (1.8.11)
Requirement already satisfied: pyproj in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from geopandas->atlite==0.0.4.dev330+g2fbdd9f) (2.6.1.post1)
Requirement already satisfied: tqdm in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from cdsapi->atlite==0.0.4.dev330+g2fbdd9f) (4.46.0)
Requirement already satisfied: pyparsing>=2.1.6 in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from snuggs>=1.4.1->rasterio>=1.0->atlite==0.0.4.dev330+g2fbdd9f) (2.4.7)
Requirement already satisfied: munch in /home/pypsa/miniconda3/envs/atlite/lib/python3.7/site-packages (from fiona->geopandas->atlite==0.0.4.dev330+g2fbdd9f) (2.5.0)
Building wheels for collected packages: atlite
  Building wheel for atlite (setup.py) ... done
  Created wheel for atlite: filename=atlite-0.0.4.dev330+g2fbdd9f-py2.py3-none-any.whl size=63453 sha256=d0a94b784da2cb309c2b0913df8c9e52023788bf8eaf852cad4ee594e5c033e9
  Stored in directory: /tmp/pip-ephem-wheel-cache-53fc5lbo/wheels/8b/16/63/70c28877db9b6c491a9550dbcc78dd21b3704cc10c6d9ca4f8
Successfully built atlite
Installing collected packages: atlite
Successfully installed atlite-0.0.4.dev330+g2fbdd9f
```

Is this intended behaviour?
I presume it is related to the changes with how the versioning works.

**Comment by coroa** [comment]
Not intended, agreed looks like being caused by setuptools_scm.

Unfortunately, can't reproduce; works for me on windows and linux. Damn. Will have to think about what could possibly cause this.

**Comment by coroa** [comment]
Can’t find anything in the trackers of setuptools and setuptools_scm, which seems related.

If you can, please try whether the installation of setuptools_scm using conda, as like ‘conda install setuptools_scm’, before calling ’pip’, fixes this.

**Comment by FabianHofmann** [comment]
Using the `-e` argument might be saver?

**Comment by euronion** [comment]
> Using the -e argument might be saver?

`pip install -e .` alone produces the same result, tried it before.

> If you can, please try whether the installation of setuptools_scm using conda, as like ‘conda install setuptools_scm’, before calling ’pip’, fixes this.

```
conda install -c conda-forge setuptools_scm
```
does the trick.
`pip install` and `pip install -e` both work after installing `setuptools_scm` from `conda-forge` in the environment.
